version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kintone-btn-cron"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iwy7361370bi"
s3_prefix = "kintone-btn-cron"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
